### ISSUE TITLE
Proper handle "DB Error: no database selected"

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/uk.co.compucorp.civicrm.mailjet#12]
The problem started 13.12. and lasted until I restarted service mailjet_amqp. This problem produced many logs in CiviCRM.

Dec 21 07:35:13  [info] $backTrace = 0 /var/www/civicrm-4.6.7/CRM/Core/Error.php(897): CRM_Core_Error::backtrace("backTrace", TRUE)
1 [internal function](): CRM_Core_Error::exceptionHandler(Object(DB_Error))
2 /var/www/civicrm-4.6.7/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
3 /var/www/civicrm-4.6.7/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: no database selected", -14, 16, (Array:2), "SET NAMES utf8 [nativecode=2006 ** MySQL server has gone away]")
4 /var/www/civicrm-4.6.7/packages/PEAR.php(564): DB_Error->DB_Error(-14, 16, (Array:2), "SET NAMES utf8 [nativecode=2006 ** MySQL server has gone away]")
5 /var/www/civicrm-4.6.7/packages/DB/common.php(1905): PEAR->raiseError(NULL, -14, NULL, NULL, "SET NAMES utf8 [nativecode=2006 ** MySQL server has gone away]", "DB_Error", TRUE)
6 /var/www/civicrm-4.6.7/packages/DB/mysql.php(895): DB_common->raiseError(-14, NULL, NULL, NULL, "2006 ** MySQL server has gone away")
7 /var/www/civicrm-4.6.7/packages/DB/mysql.php(309): DB_mysql->mysqlRaiseError(-14)
8 /var/www/civicrm-4.6.7/packages/DB/common.php(1216): DB_mysql->simpleQuery("SET NAMES utf8")
9 /var/www/civicrm-4.6.7/packages/DB/DataObject.php(2442): DB_common->query("SET NAMES utf8")
10 /var/www/civicrm-4.6.7/packages/DB/DataObject.php(1634): DB_DataObject->_query("SET NAMES utf8")
11 /var/www/civicrm-4.6.7/CRM/Core/DAO.php(325): DB_DataObject->query("SET NAMES utf8")
12 /var/www/civicrm-4.6.7/CRM/Core/DAO.php(363): CRM_Core_DAO->query("SET NAMES utf8")
13 /var/www/civicrm-4.6.7/CRM/Core/DAO.php(86): CRM_Core_DAO->initialize()
14 /var/www/civicrm-4.6.7/CRM/Core/DAO/Email.php(163): CRM_Core_DAO->__construct()
15 /var/www/civicrm-4.6.7/api/v3/utils.php(1765): CRM_Core_DAO_Email->__construct()
16 /var/www/civicrm-4.6.7/api/v3/Generic.php(106): _civicrm_api_get_fields("Email", TRUE, (Array:3))
17 /var/www/civicrm-4.6.7/Civi/API/Provider/MagicFunctionProvider.php(86): civicrm_api3_generic_getfields((Array:9))
18 /var/www/civicrm-4.6.7/Civi/API/Kernel.php(96): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
19 /var/www/civicrm-4.6.7/api/api.php(23): Civi\API\Kernel->run("Email", "getfields", (Array:2), NULL)
20 /var/www/civicrm-4.6.7/api/api.php(43): civicrm_api("Email", "getfields", (Array:2))
21 /var/www/civicrm-4.6.7/api/api.php(83): civicrm_api3("Email", "getfields", (Array:1))
22 /var/www/civicrm-4.6.7/Civi/API/Kernel.php(350): _civicrm_api3_api_getfields((Array:9))
23 /var/www/civicrm-4.6.7/Civi/API/Kernel.php(276): Civi\API\Kernel->createError("DB Error: no database selected", (Array:0), (Array:9), 0)
24 /var/www/civicrm-4.6.7/Civi/API/Kernel.php(111): Civi\API\Kernel->formatException(Object(CiviCRM_API3_Exception), (Array:9))
25 /var/www/civicrm-4.6.7/api/api.php(23): Civi\API\Kernel->run("Email", "get", (Array:3), NULL)
26 /var/www/civicrm-4.6.7/api/api.php(43): civicrm_api("Email", "get", (Array:3))
27 /var/www/civi.custom/extensions/mailjet/CRM/Mailjet/Page/EndPoint.php(154): civicrm_api3("Email", "get", (Array:2))
28 /var/www/civi.custom/extensions/mailjet/amqp/consumer.php(45): CRM_Mailjet_Page_EndPoint->processMessage("{\"event\":\"bounce\",\"time\":1482302106,\"MessageID\":19140415817907870,\"e...")
29 [internal function](): {closure}(Object(PhpAmqpLib\Message\AMQPMessage))
30 /var/www/civi.custom/extensions/mailjet/amqp/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(972): call_user_func(Object(Closure), Object(PhpAmqpLib\Message\AMQPMessage))
31 [internal function](): PhpAmqpLib\Channel\AMQPChannel->basic_deliver(Object(PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
32 /var/www/civi.custom/extensions/mailjet/amqp/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(197): call_user_func((Array:2), Object(PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
33 /var/www/civi.custom/extensions/mailjet/amqp/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(393): PhpAmqpLib\Channel\AbstractChannel->dispatch("60,60", "^_amq.ctag-Vz3wf1I0Cgpk248XIUkl9Q^@^@^@^@^@^@W<FB>^@^Gmailjet^Nmailjet.bounce", Object(PhpAmqpLib\Message\AMQPMessage))
34 /var/www/civi.custom/extensions/mailjet/amqp/consumer.php(71): PhpAmqpLib\Channel\AbstractChannel->wait()
35 {main}

**Comment by rthouvenin** [comment]
Error handling and recovering from it has changed a log since then, and we are not experiencing this problem anymore. Closing
