### ISSUE TITLE
Mailjet Events not parsed properly

### ISSUE THREAD

**Issue by pbatroff** [WeMoveEU/uk.co.compucorp.civicrm.mailjet#13]
Events aren't parsed properly. According to the [documentation](https://dev.mailjet.com/guides/index.html?php#endpoint-url), events are delivered in an JSON array of event objects. The objects are grouped by all events during one second.

The Event Objects are parsed in ```CRM_Mailjet_Logic_Message```, but since it is an array data cannot be looked up. This can be tested very easily in the event API, where test events can be triggered. I used the bounce testing trigger, and just send the notification to the endpoint.

Incoming Data: (via json_encode on the post data)
`"[{\"event\":\"bounce\",\"time\":1562315087,\"MessageID\":0,\"email\":\"\",\"mj_campaign_id\":0,\"mj_contact_id\":0,\"customcampaign\":\"\",\"CustomID\":\"\",\"Payload\":\"\",\"blocked\":\"\",\"hard_bounce\":\"\",\"error_related_to\":\"\",\"error\":\"\"}]"
`

Error Message: ```$ENDPOINT EVENT = Invalid JSON or no event```

A fix in my opinion would be to parse the post message in ```CRM_Mailjet_Page_EndPoint```, and use a foreach to parse all bounce event objects one after another. I'll work on a PR. I'm just wondering that noone else had this problem ...

**Comment by tttp** [comment]
Mailjet has two modes, one batching the events the other with one call per event if I recall. The code is handling the later, your config wants the former

in your PR, could you check the type of the data, if it's an array, your foreach, if not, the data is the event?

Thanks for contributing!

**Comment by pbatroff** [comment]
Ok, good to know! How can I influence the mode? Haven't found any configuration in that regard - and the documentation always refers to a list ... 

Anyways - will consider that in the Code. Will look into it next week!

**Comment by tttp** [comment]
It's the "group event" checkbox in https://app.mailjet.com/account/triggers
