### ISSUE TITLE
Bounce Handling Hook

### ISSUE THREAD

**Issue by pbatroff** [WeMoveEU/uk.co.compucorp.civicrm.mailjet#14]
In case of custom bounce handling or additional bounce parameters, a hook would be nice to address this issue. Hook would come in `CRM_Mailjet_Page_EndPoint::processMessage($msg)`.

Use Case: Inject additional Parameters by `civicrm_alterMailParams`, and extract/use them during the hook execution. Should be unobtrusive for all other cases.

**Comment by tttp** [comment]
Out of curiousity, what is your use case? what extra param do you need?

**Comment by pbatroff** [comment]
The use case is that we need to handle bounces from [donrec](https://github.com/systopia/de.systopia.donrec) seperatly. In this case, if a bounce occurs we need to withdraw the donation receipt and create a separate activity. 

For that we need information in the Payload (see Mailjet [custom headers (X-MJ-EventPayload) ](https://dev.mailjet.com/smtp-relay/custom-headers/)), and be able to retrieve them when a bounce event is happening. In this specific case that would be profile_id, contribution_id, contact_id and a timestamp. 

Generally all application specific content can be sent (JSON encoded) in X-MJ-EventPayload, and retrieved in the webhook event under Payload.

**Comment by pbatroff** [comment]
Closed in the above PR merge. Thanks!
