### ISSUE TITLE
Extend integer type for mj_campaign_id

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/uk.co.compucorp.civicrm.mailjet#6]
It's possible that mj_campaign_id has value higher than INT limit 
http://dev.mysql.com/doc/refman/5.7/en/integer-types.html

Convert `civicrm_mailing_mailjet_event.mj_campaign_id` and 
`civicrm_mailing_mailjet_event.mj_contact_id` to BIGINT.

**Comment by a-sassmannshausen** [comment]
Ran into this issue, had to fix it manually on some customer databases.

**Comment by rthouvenin** [comment]
Fixed for new installs (no migration included in #18)
